# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_Intro.ipynb.

# %% auto 0
__all__ = ['say_hello', 'say_hello_basque']

# %% ../nbs/00_Intro.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_Intro.ipynb 4
def say_hello_basque(to):
    "Say hello to somebody, in Basque"
    return f'Kaixo {to}!'
